---

version: '2'
services:
  openldap:
    container_name: jitsi-meet
    image: arola1982/jitsi-meet:latest
    build:
      context: .
      args:
        DOMAIN: ${DOMAIN}
        JICOFO_AUTH_PASSWORD: ${JICOFO_AUTH_PASSWORD}
        JICOFO_SECRET: ${JICOFO_SECRET}
        JVB_SECRET: ${JVB_SECRET}
    volumes_from:
      - container:nginx:ro
    ports:
      - "443:443"
      - "5222:5222"
      - "5269:5269"
      - "5280:5280"
      - "5347:5347"
      - "10000-10010:10000-10010/udp"

networks:
  default:
    external:
      name: arola_net
