---

version: '2'
services:
  jitsi-meet:
    container_name: jitsi-meet
    image: arola1982/jitsi-meet:latest
    build:
      context: .
      args:
        DOMAIN: ${DOMAIN}
        TLD: ${TLD}
        JICOFO_AUTH_PASSWORD: ${JICOFO_AUTH_PASSWORD}
        JICOFO_SECRET: ${JICOFO_SECRET}
        JVB_SECRET: ${JVB_SECRET}
        JICOFO_RAM: ${JICOFO_RAM}
        JVB_RAM: ${JVB_RAM}
        LOCAL_ADDRESS: ${LOCAL_ADDRESS}
        PUBLIC_ADDRESS: ${PUBLIC_ADDRESS}
    volumes_from:
      - container:nginx:ro
    ports:
      - "10000-10010:10000-10010/udp"

networks:
  default:
    external:
      name: arola_net
