#!/bin/bash

sed -ri "s/DOCKER_DOMAIN/${DOMAIN}/g" /etc/nginx/sites-enabled/${DOMAIN}
sed -ri "s/DOCKER_TLD/${TLD}/g" /etc/nginx/sites-enabled/${DOMAIN}

sed -ri "s/Xmx3072m/Xmx${JICOFO_RAM}" /usr/share/jicofo/jicofo.sh
sed -ri "s/# VIDEOBRIDGE_MAX_MEMORY=3072m/VIDEOBRIDGE_MAX_MEMORY=${JVB_RAM}" /usr/share/jitsi-videobridge/lib/videobridge.rc

unset TLD
unset DOMAIN

/etc/init.d/nginx start
/etc/init.d/prosody start
/etc/init.d/jicofo start

/etc/init.d/jitsi-videobridge start

sleep 2

tail -f /var/log/jitsi/jvb.log
