#!/bin/bash

sed -ri "s/DOCKER_DOMAIN/${DOMAIN}/g" /etc/nginx/sites-enabled/${DOMAIN}
sed -ri "s/DOCKER_TLD/${TLD}/g" /etc/nginx/sites-enabled/${DOMAIN}

unset TLD
unset DOMAIN

/etc/init.d/nginx start
/etc/init.d/prosody start
/etc/init.d/jicofo start

/etc/init.d/jitsi-videobridge start

sleep 2

tail -f /var/log/jitsi/jvb.log
